GITHUB_APP_ID: "73929ffb0e3e890fcd7f"
GITHUB_APP_SECRET: "42e47878f1c79889c95dea85c8e11260db99d9a6"
FACEBOOK_APP_ID: "1754152694873810"
FACEBOOK_APP_SECRET: "d8d995f689b1468c30b4ee9165530c5d"
TWITTER_API_KEY: "fwpq96M2ge084a3dUlcGs1fMR"
TWITTER_API_SECRET: "4Kq9zFWznCO7BenByyaPXa7tWvqvBWyeFx4oXXjYExwMhjy3QO"

mail_url_development: "localhost:3000"
mail_url_production: "malkoring.net"
