# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c8cbf700a7ee05209b63785fe4768c7fdc91418aa3472115c748432e67bef106e7256062278d6394ccf8c23c216a2c39b385029311d321576b28da11d4cc83

test:
  secret_key_base: 0cbfa956b28efffc650fbab68ade7e5ae06ad67f7bee2f40a141d5437abc1ac0781af807563e5560db29a610067eb0ebfffdbfbdf19a3d33df1eb9518c4a7058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
